version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/crypto
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecretkey123
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  redis_dev_data:
