version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
