version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: banking_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/banking

  mongo:
    image: mongo:7
    container_name: banking_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: banking_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/ppchu.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/ppchu.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - app
    restart: always

volumes:
  mongodb_data:
