version: "3.8"

services:
  app:
    build: ./app
    container_name: banking_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/banking

  mongo:
    image: mongo:7
    container_name: banking_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: banking_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # ТУК ВНИМАНИЕ — това го сменяш за dev или prod:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf

      # Тези само за production:
      # - /etc/letsencrypt/live/ppchu.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      # - /etc/letsencrypt/live/ppchu.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - app
    restart: always

  mongo-express:
    image: mongo-express
    container_name: banking_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=1234
    depends_on:
      - mongo

volumes:
  mongodb_data:
