name: Test & Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (incl. devDependencies)
        run: npm install
        working-directory: ./app

      - name: Run Jest tests
        run: npm test
        working-directory: ./app

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Run deploy script on EC2
        run: ssh -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.EC2_HOST }} 'bash /home/ubuntu/crypto-app/deploy.sh'
